In [15]:
import pandas as pd
import os


data_path ="../data/raw/"

files = os.listdir(data_path)

print("Files available:")
for file in files:
    print(file)
    
customers = pd.read_csv(
    data_path + "olist_customers_dataset.csv"
)

orders = pd.read_csv(
    data_path + "olist_orders_dataset.csv"
)

order_items = pd.read_csv(
    data_path + "olist_order_items_dataset.csv"
)

order_payments = pd.read_csv(
    data_path + "olist_order_payments_dataset.csv"
)

order_reviews = pd.read_csv(
    data_path + "olist_order_reviews_dataset.csv"
)

products = pd.read_csv(
    data_path + "olist_products_dataset.csv"
)

sellers = pd.read_csv(
    data_path + "olist_sellers_dataset.csv"
)

product_category_translation = pd.read_csv(
    data_path + "product_category_name_translation.csv"
)

geolocation = pd.read_csv(
    data_path + "olist_geolocation_dataset.csv"
)


tables = {
    "CUSTOMERS": customers,
    "ORDERS": orders,
    "ORDER_ITEMS": order_items,
    "ORDER_PAYMENTS": order_payments,
    "ORDER_REVIEWS": order_reviews,
    "PRODUCTS": products,
    "SELLERS": sellers,
    "PRODUCT_CATEGORY_TRANSLATION": product_category_translation,
    "GEOLOCATION": geolocation
}

for table_name, df in tables.items():
    print(f"{table_name}: {df.shape}")

for table_name, df in tables.items():
    
    print("=" * 70)
    print(table_name)
    print("=" * 70)
    
    print(df.columns.tolist())
    print()

for table_name, df in tables.items():
    
    print("=" * 70)
    print(table_name)
    print("=" * 70)
    
    print(df.dtypes)
    print()

summary = []

for table_name, df in tables.items():
    
    for column in df.columns:
        
        summary.append({
            "Table": table_name,
            "Column": column,
            "Data_Type": str(df[column].dtype),
            "Rows": df.shape[0],
            "Columns_Count": df.shape[1]
        })

data_dictionary = pd.DataFrame(summary)

data_dictionary

key_information = {
    
    "CUSTOMERS": {
        "customer_id": "PK",
        "customer_zip_code_prefix": "FK"
    },
    
    "ORDERS": {
        "order_id": "PK",
        "customer_id": "FK"
    },
    
    "ORDER_ITEMS": {
        "order_id": "FK",
        "order_item_id": "PK",
        "product_id": "FK",
        "seller_id": "FK"
    },
    
    "ORDER_PAYMENTS": {
        "order_id": "FK",
        "payment_sequential": "PK"
    },
    
    "ORDER_REVIEWS": {
        "review_id": "PK",
        "order_id": "FK"
    },
    
    "PRODUCTS": {
        "product_id": "PK",
        "product_category_name": "FK"
    },
    
    "SELLERS": {
        "seller_id": "PK",
        "seller_zip_code_prefix": "FK"
    },
    
    "PRODUCT_CATEGORY_TRANSLATION": {
        "product_category_name": "PK"
    },
    
    "GEOLOCATION": {
        "geolocation_zip_code_prefix": "PK"
    }
}

dictionary = []

for table_name, df in tables.items():
    
    for column in df.columns:
        
        key = key_information.get(
            table_name, {}
        ).get(column, "")
        
        dictionary.append({
            "Table": table_name,
            "Column": column,
            "Data Type": str(df[column].dtype),
            "Key": key
        })

data_dictionary = pd.DataFrame(dictionary)

data_dictionary

for table_name, df in tables.items():
    
    print("=" * 70)
    print(table_name)
    print("=" * 70)
    
    display(df.head())


for table_name, df in tables.items():
    
    print("=" * 80)
    print(f"TABLE: {table_name}")
    print("=" * 80)
    
    print("Shape:", df.shape)
    
    print("\nColumns:")
    print(df.columns.tolist())
    
    print("\nData Types:")
    print(df.dtypes)
    
    print("\nFirst 3 Records:")
    display(df.head(3))
    
    print("\n")

data_dictionary.to_csv(
    "../output/data_dictionary.csv",
    index=False
)

os.makedirs("../output", exist_ok=True)

data_dictionary.to_csv(
    "../output/data_dictionary.csv",
    index=False
)

Files available:
.ipynb_checkpoints
olist_customers_dataset.csv
olist_geolocation_dataset.csv
olist_orders_dataset.csv
olist_order_items_dataset.csv
olist_order_payments_dataset.csv
olist_order_reviews_dataset.csv
olist_products_dataset.csv
olist_sellers_dataset.csv
product_category_name_translation.csv
CUSTOMERS: (99441, 5)
ORDERS: (99441, 8)
ORDER_ITEMS: (112650, 7)
ORDER_PAYMENTS: (103886, 5)
ORDER_REVIEWS: (99224, 7)
PRODUCTS: (32951, 9)
SELLERS: (3095, 4)
PRODUCT_CATEGORY_TRANSLATION: (71, 2)
GEOLOCATION: (1000163, 5)
======================================================================
CUSTOMERS
======================================================================
['customer_id', 'customer_unique_id', 'customer_zip_code_prefix', 'customer_city', 'customer_state']

======================================================================
ORDERS
======================================================================
['order_id', 'customer_id', 'order_status', 'order_purchase_timestamp', 'order_approved_at', 'order_delivered_carrier_date', 'order_delivered_customer_date', 'order_estimated_delivery_date']

======================================================================
ORDER_ITEMS
======================================================================
['order_id', 'order_item_id', 'product_id', 'seller_id', 'shipping_limit_date', 'price', 'freight_value']

======================================================================
ORDER_PAYMENTS
======================================================================
['order_id', 'payment_sequential', 'payment_type', 'payment_installments', 'payment_value']

======================================================================
ORDER_REVIEWS
======================================================================
['review_id', 'order_id', 'review_score', 'review_comment_title', 'review_comment_message', 'review_creation_date', 'review_answer_timestamp']

======================================================================
PRODUCTS
======================================================================
['product_id', 'product_category_name', 'product_name_lenght', 'product_description_lenght', 'product_photos_qty', 'product_weight_g', 'product_length_cm', 'product_height_cm', 'product_width_cm']

======================================================================
SELLERS
======================================================================
['seller_id', 'seller_zip_code_prefix', 'seller_city', 'seller_state']

======================================================================
PRODUCT_CATEGORY_TRANSLATION
======================================================================
['product_category_name', 'product_category_name_english']

======================================================================
GEOLOCATION
======================================================================
['geolocation_zip_code_prefix', 'geolocation_lat', 'geolocation_lng', 'geolocation_city', 'geolocation_state']

======================================================================
CUSTOMERS
======================================================================
customer_id                   str
customer_unique_id            str
customer_zip_code_prefix    int64
customer_city                 str
customer_state                str
dtype: object

======================================================================
ORDERS
======================================================================
order_id                         str
customer_id                      str
order_status                     str
order_purchase_timestamp         str
order_approved_at                str
order_delivered_carrier_date     str
order_delivered_customer_date    str
order_estimated_delivery_date    str
dtype: object

======================================================================
ORDER_ITEMS
======================================================================
order_id                   str
order_item_id            int64
product_id                 str
seller_id                  str
shipping_limit_date        str
price                  float64
freight_value          float64
dtype: object

======================================================================
ORDER_PAYMENTS
======================================================================
order_id                    str
payment_sequential        int64
payment_type                str
payment_installments      int64
payment_value           float64
dtype: object

======================================================================
ORDER_REVIEWS
======================================================================
review_id                    str
order_id                     str
review_score               int64
review_comment_title         str
review_comment_message       str
review_creation_date         str
review_answer_timestamp      str
dtype: object

======================================================================
PRODUCTS
======================================================================
product_id                        str
product_category_name             str
product_name_lenght           float64
product_description_lenght    float64
product_photos_qty            float64
product_weight_g              float64
product_length_cm             float64
product_height_cm             float64
product_width_cm              float64
dtype: object

======================================================================
SELLERS
======================================================================
seller_id                   str
seller_zip_code_prefix    int64
seller_city                 str
seller_state                str
dtype: object

======================================================================
PRODUCT_CATEGORY_TRANSLATION
======================================================================
product_category_name            str
product_category_name_english    str
dtype: object

======================================================================
GEOLOCATION
======================================================================
geolocation_zip_code_prefix      int64
geolocation_lat                float64
geolocation_lng                float64
geolocation_city                   str
geolocation_state                  str
dtype: object

======================================================================
CUSTOMERS
======================================================================

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,mogi das cruzes,SP
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP

======================================================================
ORDERS
======================================================================

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00

======================================================================
ORDER_ITEMS
======================================================================

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14

======================================================================
ORDER_PAYMENTS
======================================================================

,order_id,payment_sequential,payment_type,payment_installments,payment_value
0,b81ef226f3fe1789b1e8b2acac839d17,1,credit_card,8,99.33
1,a9810da82917af2d9aefd1278f1dcfa0,1,credit_card,1,24.39
2,25e8ea4e93396b6fa0d3dd708e76c1bd,1,credit_card,1,65.71
3,ba78997921bbcdc1373bb41e913ab953,1,credit_card,8,107.78
4,42fdf880ba16b47b59251dd489d4441a,1,credit_card,2,128.45

======================================================================
ORDER_REVIEWS
======================================================================

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
0,7bc2406110b926393aa56f80a40eba40,73fc7af87114b39712e6da79b0a377eb,4,NaN,NaN,2018-01-18 00:00:00,2018-01-18 21:46:59
1,80e641a11e56f04c1ad469d5645fdfde,a548910a1c6147796b98fdf73dbeba33,5,NaN,NaN,2018-03-10 00:00:00,2018-03-11 03:05:13
2,228ce5500dc1d8e020d8d1322874b6f0,f9e4b658b201a9f2ecdecbb34bed034b,5,NaN,NaN,2018-02-17 00:00:00,2018-02-18 14:36:24
3,e64fb393e7b32834bb789ff8bb30750e,658677c97b385a9be170737859d3511b,5,NaN,Recebi bem antes do prazo estipulado.,2017-04-21 00:00:00,2017-04-21 22:02:06
4,f7c4243c7fe1938f181bec41a392bdeb,8e6bfb81e283fa7e4f11123a3fb894f1,5,NaN,Parabéns lojas lannister adorei comprar pela I...,2018-03-01 00:00:00,2018-03-02 10:26:53

======================================================================
PRODUCTS
======================================================================

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumaria,40.0,287.0,1.0,225.0,16.0,10.0,14.0
1,3aa071139cb16b67ca9e5dea641aaa2f,artes,44.0,276.0,1.0,1000.0,30.0,18.0,20.0
2,96bd76ec8810374ed1b65e291975717f,esporte_lazer,46.0,250.0,1.0,154.0,18.0,9.0,15.0
3,cef67bcfe19066a932b7673e239eb23d,bebes,27.0,261.0,1.0,371.0,26.0,4.0,26.0
4,9dc1a7de274444849c219cff195d0b71,utilidades_domesticas,37.0,402.0,4.0,625.0,20.0,17.0,13.0

======================================================================
SELLERS
======================================================================

,seller_id,seller_zip_code_prefix,seller_city,seller_state
0,3442f8959a84dea7ee197c632cb2df15,13023,campinas,SP
1,d1b65fc7debc3361ea86b5f14c68d2e2,13844,mogi guacu,SP
2,ce3ad9de960102d0677a81f5d0bb7b2d,20031,rio de janeiro,RJ
3,c0f3eea2e14555b6faeea3dd58c1b1c3,4195,sao paulo,SP
4,51a04a8a6bdcb23deccc82b0b80742cf,12914,braganca paulista,SP

======================================================================
PRODUCT_CATEGORY_TRANSLATION
======================================================================

    product_category_name product_category_name_english
0            beleza_saude                 health_beauty
1  informatica_acessorios         computers_accessories
2              automotivo                          auto
3         cama_mesa_banho                bed_bath_table
4        moveis_decoracao               furniture_decor

======================================================================
GEOLOCATION
======================================================================

,geolocation_zip_code_prefix,geolocation_lat,geolocation_lng,geolocation_city,geolocation_state
0,1037,-23.545621,-46.639292,sao paulo,SP
1,1046,-23.546081,-46.644820,sao paulo,SP
2,1046,-23.546129,-46.642951,sao paulo,SP
3,1041,-23.544392,-46.639499,sao paulo,SP
4,1035,-23.541578,-46.641607,sao paulo,SP

================================================================================
TABLE: CUSTOMERS
================================================================================
Shape: (99441, 5)

Columns:
['customer_id', 'customer_unique_id', 'customer_zip_code_prefix', 'customer_city', 'customer_state']

Data Types:
customer_id                   str
customer_unique_id            str
customer_zip_code_prefix    int64
customer_city                 str
customer_state                str
dtype: object

First 3 Records:

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP

================================================================================
TABLE: ORDERS
================================================================================
Shape: (99441, 8)

Columns:
['order_id', 'customer_id', 'order_status', 'order_purchase_timestamp', 'order_approved_at', 'order_delivered_carrier_date', 'order_delivered_customer_date', 'order_estimated_delivery_date']

Data Types:
order_id                         str
customer_id                      str
order_status                     str
order_purchase_timestamp         str
order_approved_at                str
order_delivered_carrier_date     str
order_delivered_customer_date    str
order_estimated_delivery_date    str
dtype: object

First 3 Records:

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00

================================================================================
TABLE: ORDER_ITEMS
================================================================================
Shape: (112650, 7)

Columns:
['order_id', 'order_item_id', 'product_id', 'seller_id', 'shipping_limit_date', 'price', 'freight_value']

Data Types:
order_id                   str
order_item_id            int64
product_id                 str
seller_id                  str
shipping_limit_date        str
price                  float64
freight_value          float64
dtype: object

First 3 Records:

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.9,13.29
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.9,19.93
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.0,17.87

================================================================================
TABLE: ORDER_PAYMENTS
================================================================================
Shape: (103886, 5)

Columns:
['order_id', 'payment_sequential', 'payment_type', 'payment_installments', 'payment_value']

Data Types:
order_id                    str
payment_sequential        int64
payment_type                str
payment_installments      int64
payment_value           float64
dtype: object

First 3 Records:

,order_id,payment_sequential,payment_type,payment_installments,payment_value
0,b81ef226f3fe1789b1e8b2acac839d17,1,credit_card,8,99.33
1,a9810da82917af2d9aefd1278f1dcfa0,1,credit_card,1,24.39
2,25e8ea4e93396b6fa0d3dd708e76c1bd,1,credit_card,1,65.71

================================================================================
TABLE: ORDER_REVIEWS
================================================================================
Shape: (99224, 7)

Columns:
['review_id', 'order_id', 'review_score', 'review_comment_title', 'review_comment_message', 'review_creation_date', 'review_answer_timestamp']

Data Types:
review_id                    str
order_id                     str
review_score               int64
review_comment_title         str
review_comment_message       str
review_creation_date         str
review_answer_timestamp      str
dtype: object

First 3 Records:

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
0,7bc2406110b926393aa56f80a40eba40,73fc7af87114b39712e6da79b0a377eb,4,NaN,NaN,2018-01-18 00:00:00,2018-01-18 21:46:59
1,80e641a11e56f04c1ad469d5645fdfde,a548910a1c6147796b98fdf73dbeba33,5,NaN,NaN,2018-03-10 00:00:00,2018-03-11 03:05:13
2,228ce5500dc1d8e020d8d1322874b6f0,f9e4b658b201a9f2ecdecbb34bed034b,5,NaN,NaN,2018-02-17 00:00:00,2018-02-18 14:36:24

================================================================================
TABLE: PRODUCTS
================================================================================
Shape: (32951, 9)

Columns:
['product_id', 'product_category_name', 'product_name_lenght', 'product_description_lenght', 'product_photos_qty', 'product_weight_g', 'product_length_cm', 'product_height_cm', 'product_width_cm']

Data Types:
product_id                        str
product_category_name             str
product_name_lenght           float64
product_description_lenght    float64
product_photos_qty            float64
product_weight_g              float64
product_length_cm             float64
product_height_cm             float64
product_width_cm              float64
dtype: object

First 3 Records:

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumaria,40.0,287.0,1.0,225.0,16.0,10.0,14.0
1,3aa071139cb16b67ca9e5dea641aaa2f,artes,44.0,276.0,1.0,1000.0,30.0,18.0,20.0
2,96bd76ec8810374ed1b65e291975717f,esporte_lazer,46.0,250.0,1.0,154.0,18.0,9.0,15.0

================================================================================
TABLE: SELLERS
================================================================================
Shape: (3095, 4)

Columns:
['seller_id', 'seller_zip_code_prefix', 'seller_city', 'seller_state']

Data Types:
seller_id                   str
seller_zip_code_prefix    int64
seller_city                 str
seller_state                str
dtype: object

First 3 Records:

,seller_id,seller_zip_code_prefix,seller_city,seller_state
0,3442f8959a84dea7ee197c632cb2df15,13023,campinas,SP
1,d1b65fc7debc3361ea86b5f14c68d2e2,13844,mogi guacu,SP
2,ce3ad9de960102d0677a81f5d0bb7b2d,20031,rio de janeiro,RJ

================================================================================
TABLE: PRODUCT_CATEGORY_TRANSLATION
================================================================================
Shape: (71, 2)

Columns:
['product_category_name', 'product_category_name_english']

Data Types:
product_category_name            str
product_category_name_english    str
dtype: object

First 3 Records:

    product_category_name product_category_name_english
0            beleza_saude                 health_beauty
1  informatica_acessorios         computers_accessories
2              automotivo                          auto

================================================================================
TABLE: GEOLOCATION
================================================================================
Shape: (1000163, 5)

Columns:
['geolocation_zip_code_prefix', 'geolocation_lat', 'geolocation_lng', 'geolocation_city', 'geolocation_state']

Data Types:
geolocation_zip_code_prefix      int64
geolocation_lat                float64
geolocation_lng                float64
geolocation_city                   str
geolocation_state                  str
dtype: object

First 3 Records:

,geolocation_zip_code_prefix,geolocation_lat,geolocation_lng,geolocation_city,geolocation_state
0,1037,-23.545621,-46.639292,sao paulo,SP
1,1046,-23.546081,-46.644820,sao paulo,SP
2,1046,-23.546129,-46.642951,sao paulo,SP

,Table,Column,Missing_Count,Total_Rows,Missing_Percentage
0,CUSTOMERS,customer_id,0,99441,0.00
1,CUSTOMERS,customer_unique_id,0,99441,0.00
2,CUSTOMERS,customer_zip_code_prefix,0,99441,0.00
3,CUSTOMERS,customer_city,0,99441,0.00
4,CUSTOMERS,customer_state,0,99441,0.00
5,ORDERS,order_id,0,99441,0.00
6,ORDERS,customer_id,0,99441,0.00
7,ORDERS,order_status,0,99441,0.00
8,ORDERS,order_purchase_timestamp,0,99441,0.00
9,ORDERS,order_approved_at,160,99441,0.16
10,ORDERS,order_delivered_carrier_date,1783,99441,1.79
11,ORDERS,order_delivered_customer_date,2965,99441,2.98
12,ORDERS,order_estimated_delivery_date,0,99441,0.00
13,ORDER_ITEMS,order_id,0,112650,0.00
14,ORDER_ITEMS,order_item_id,0,112650,0.00
15,ORDER_ITEMS,product_id,0,112650,0.00
16,ORDER_ITEMS,seller_id,0,112650,0.00
17,ORDER_ITEMS,shipping_limit_date,0,112650,0.00
18,ORDER_ITEMS,price,0,112650,0.00
19,ORDER_ITEMS,freight_value,0,112650,0.00
20,ORDER_PAYMENTS,order_id,0,103886,0.00
21,ORDER_PAYMENTS,payment_sequential,0,103886,0.00
22,ORDER_PAYMENTS,payment_type,0,103886,0.00
23,ORDER_PAYMENTS,payment_installments,0,103886,0.00
24,ORDER_PAYMENTS,payment_value,0,103886,0.00
25,ORDER_REVIEWS,review_id,0,99224,0.00
26,ORDER_REVIEWS,order_id,0,99224,0.00
27,ORDER_REVIEWS,review_score,0,99224,0.00
28,ORDER_REVIEWS,review_comment_title,87656,99224,88.34
29,ORDER_REVIEWS,review_comment_message,58247,99224,58.70
30,ORDER_REVIEWS,review_creation_date,0,99224,0.00
31,ORDER_REVIEWS,review_answer_timestamp,0,99224,0.00
32,PRODUCTS,product_id,0,32951,0.00
33,PRODUCTS,product_category_name,610,32951,1.85
34,PRODUCTS,product_name_lenght,610,32951,1.85
35,PRODUCTS,product_description_lenght,610,32951,1.85
36,PRODUCTS,product_photos_qty,610,32951,1.85
37,PRODUCTS,product_weight_g,2,32951,0.01
38,PRODUCTS,product_length_cm,2,32951,0.01
39,PRODUCTS,product_height_cm,2,32951,0.01
40,PRODUCTS,product_width_cm,2,32951,0.01
41,SELLERS,seller_id,0,3095,0.00
42,SELLERS,seller_zip_code_prefix,0,3095,0.00
43,SELLERS,seller_city,0,3095,0.00
44,SELLERS,seller_state,0,3095,0.00
45,PRODUCT_CATEGORY_TRANSLATION,product_category_name,0,71,0.00
46,PRODUCT_CATEGORY_TRANSLATION,product_category_name_english,0,71,0.00
47,GEOLOCATION,geolocation_zip_code_prefix,0,1000163,0.00
48,GEOLOCATION,geolocation_lat,0,1000163,0.00
49,GEOLOCATION,geolocation_lng,0,1000163,0.00
50,GEOLOCATION,geolocation_city,0,1000163,0.00
51,GEOLOCATION,geolocation_state,0,1000163,0.00

In [16]:

missing_summary = []

for table_name, df in tables.items():

    for column in df.columns:

        missing_count = df[column].isnull().sum()
        total_count = len(df)
        missing_percentage = (missing_count / total_count) * 100

        missing_summary.append({
            "Table": table_name,
            "Column": column,
            "Missing_Count": missing_count,
            "Total_Rows": total_count,
            "Missing_Percentage": round(missing_percentage, 2)
        })

missing_df = pd.DataFrame(missing_summary)

missing_df

,Table,Column,Missing_Count,Total_Rows,Missing_Percentage
0,CUSTOMERS,customer_id,0,99441,0.00
1,CUSTOMERS,customer_unique_id,0,99441,0.00
2,CUSTOMERS,customer_zip_code_prefix,0,99441,0.00
3,CUSTOMERS,customer_city,0,99441,0.00
4,CUSTOMERS,customer_state,0,99441,0.00
5,ORDERS,order_id,0,99441,0.00
6,ORDERS,customer_id,0,99441,0.00
7,ORDERS,order_status,0,99441,0.00
8,ORDERS,order_purchase_timestamp,0,99441,0.00
9,ORDERS,order_approved_at,160,99441,0.16
10,ORDERS,order_delivered_carrier_date,1783,99441,1.79
11,ORDERS,order_delivered_customer_date,2965,99441,2.98
12,ORDERS,order_estimated_delivery_date,0,99441,0.00
13,ORDER_ITEMS,order_id,0,112650,0.00
14,ORDER_ITEMS,order_item_id,0,112650,0.00
15,ORDER_ITEMS,product_id,0,112650,0.00
16,ORDER_ITEMS,seller_id,0,112650,0.00
17,ORDER_ITEMS,shipping_limit_date,0,112650,0.00
18,ORDER_ITEMS,price,0,112650,0.00
19,ORDER_ITEMS,freight_value,0,112650,0.00
20,ORDER_PAYMENTS,order_id,0,103886,0.00
21,ORDER_PAYMENTS,payment_sequential,0,103886,0.00
22,ORDER_PAYMENTS,payment_type,0,103886,0.00
23,ORDER_PAYMENTS,payment_installments,0,103886,0.00
24,ORDER_PAYMENTS,payment_value,0,103886,0.00
25,ORDER_REVIEWS,review_id,0,99224,0.00
26,ORDER_REVIEWS,order_id,0,99224,0.00
27,ORDER_REVIEWS,review_score,0,99224,0.00
28,ORDER_REVIEWS,review_comment_title,87656,99224,88.34
29,ORDER_REVIEWS,review_comment_message,58247,99224,58.70
30,ORDER_REVIEWS,review_creation_date,0,99224,0.00
31,ORDER_REVIEWS,review_answer_timestamp,0,99224,0.00
32,PRODUCTS,product_id,0,32951,0.00
33,PRODUCTS,product_category_name,610,32951,1.85
34,PRODUCTS,product_name_lenght,610,32951,1.85
35,PRODUCTS,product_description_lenght,610,32951,1.85
36,PRODUCTS,product_photos_qty,610,32951,1.85
37,PRODUCTS,product_weight_g,2,32951,0.01
38,PRODUCTS,product_length_cm,2,32951,0.01
39,PRODUCTS,product_height_cm,2,32951,0.01
40,PRODUCTS,product_width_cm,2,32951,0.01
41,SELLERS,seller_id,0,3095,0.00
42,SELLERS,seller_zip_code_prefix,0,3095,0.00
43,SELLERS,seller_city,0,3095,0.00
44,SELLERS,seller_state,0,3095,0.00
45,PRODUCT_CATEGORY_TRANSLATION,product_category_name,0,71,0.00
46,PRODUCT_CATEGORY_TRANSLATION,product_category_name_english,0,71,0.00
47,GEOLOCATION,geolocation_zip_code_prefix,0,1000163,0.00
48,GEOLOCATION,geolocation_lat,0,1000163,0.00
49,GEOLOCATION,geolocation_lng,0,1000163,0.00
50,GEOLOCATION,geolocation_city,0,1000163,0.00
51,GEOLOCATION,geolocation_state,0,1000163,0.00

In [17]:
missing_df[missing_df["Missing_Count"] > 0]

,Table,Column,Missing_Count,Total_Rows,Missing_Percentage
9,ORDERS,order_approved_at,160,99441,0.16
10,ORDERS,order_delivered_carrier_date,1783,99441,1.79
11,ORDERS,order_delivered_customer_date,2965,99441,2.98
28,ORDER_REVIEWS,review_comment_title,87656,99224,88.34
29,ORDER_REVIEWS,review_comment_message,58247,99224,58.70
33,PRODUCTS,product_category_name,610,32951,1.85
34,PRODUCTS,product_name_lenght,610,32951,1.85
35,PRODUCTS,product_description_lenght,610,32951,1.85
36,PRODUCTS,product_photos_qty,610,32951,1.85
37,PRODUCTS,product_weight_g,2,32951,0.01
38,PRODUCTS,product_length_cm,2,32951,0.01
39,PRODUCTS,product_height_cm,2,32951,0.01
40,PRODUCTS,product_width_cm,2,32951,0.01

In [18]:
missing_df[
    missing_df["Missing_Count"] > 0
].sort_values(
    "Missing_Percentage",
    ascending=False
)

,Table,Column,Missing_Count,Total_Rows,Missing_Percentage
28,ORDER_REVIEWS,review_comment_title,87656,99224,88.34
29,ORDER_REVIEWS,review_comment_message,58247,99224,58.70
11,ORDERS,order_delivered_customer_date,2965,99441,2.98
34,PRODUCTS,product_name_lenght,610,32951,1.85
33,PRODUCTS,product_category_name,610,32951,1.85
35,PRODUCTS,product_description_lenght,610,32951,1.85
36,PRODUCTS,product_photos_qty,610,32951,1.85
10,ORDERS,order_delivered_carrier_date,1783,99441,1.79
9,ORDERS,order_approved_at,160,99441,0.16
37,PRODUCTS,product_weight_g,2,32951,0.01
38,PRODUCTS,product_length_cm,2,32951,0.01
39,PRODUCTS,product_height_cm,2,32951,0.01
40,PRODUCTS,product_width_cm,2,32951,0.01

In [19]:
duplicate_summary = []

for table_name, df in tables.items():

    duplicate_count = df.duplicated().sum()
    total_rows = len(df)

    duplicate_summary.append({
        "Table": table_name,
        "Total_Rows": total_rows,
        "Duplicate_Rows": duplicate_count,
        "Duplicate_Percentage": round(
            (duplicate_count / total_rows) * 100, 2
        )
    })

duplicate_df = pd.DataFrame(duplicate_summary)

duplicate_df

,Table,Total_Rows,Duplicate_Rows,Duplicate_Percentage
0,CUSTOMERS,99441,0,0.00
1,ORDERS,99441,0,0.00
2,ORDER_ITEMS,112650,0,0.00
3,ORDER_PAYMENTS,103886,0,0.00
4,ORDER_REVIEWS,99224,0,0.00
5,PRODUCTS,32951,0,0.00
6,SELLERS,3095,0,0.00
7,PRODUCT_CATEGORY_TRANSLATION,71,0,0.00
8,GEOLOCATION,1000163,261831,26.18

In [20]:
datatype_summary = []

for table_name, df in tables.items():

    for column in df.columns:

        datatype_summary.append({
            "Table": table_name,
            "Column": column,
            "Data_Type": str(df[column].dtype)
        })

datatype_df = pd.DataFrame(datatype_summary)

datatype_df

                           Table                         Column Data_Type
0                      CUSTOMERS                    customer_id       str
1                      CUSTOMERS             customer_unique_id       str
2                      CUSTOMERS       customer_zip_code_prefix     int64
3                      CUSTOMERS                  customer_city       str
4                      CUSTOMERS                 customer_state       str
5                         ORDERS                       order_id       str
6                         ORDERS                    customer_id       str
7                         ORDERS                   order_status       str
8                         ORDERS       order_purchase_timestamp       str
9                         ORDERS              order_approved_at       str
10                        ORDERS   order_delivered_carrier_date       str
11                        ORDERS  order_delivered_customer_date       str
12                        ORDERS  order_estimated_delivery_date       str
13                   ORDER_ITEMS                       order_id       str
14                   ORDER_ITEMS                  order_item_id     int64
15                   ORDER_ITEMS                     product_id       str
16                   ORDER_ITEMS                      seller_id       str
17                   ORDER_ITEMS            shipping_limit_date       str
18                   ORDER_ITEMS                          price   float64
19                   ORDER_ITEMS                  freight_value   float64
20                ORDER_PAYMENTS                       order_id       str
21                ORDER_PAYMENTS             payment_sequential     int64
22                ORDER_PAYMENTS                   payment_type       str
23                ORDER_PAYMENTS           payment_installments     int64
24                ORDER_PAYMENTS                  payment_value   float64
25                 ORDER_REVIEWS                      review_id       str
26                 ORDER_REVIEWS                       order_id       str
27                 ORDER_REVIEWS                   review_score     int64
28                 ORDER_REVIEWS           review_comment_title       str
29                 ORDER_REVIEWS         review_comment_message       str
30                 ORDER_REVIEWS           review_creation_date       str
31                 ORDER_REVIEWS        review_answer_timestamp       str
32                      PRODUCTS                     product_id       str
33                      PRODUCTS          product_category_name       str
34                      PRODUCTS            product_name_lenght   float64
35                      PRODUCTS     product_description_lenght   float64
36                      PRODUCTS             product_photos_qty   float64
37                      PRODUCTS               product_weight_g   float64
38                      PRODUCTS              product_length_cm   float64
39                      PRODUCTS              product_height_cm   float64
40                      PRODUCTS               product_width_cm   float64
41                       SELLERS                      seller_id       str
42                       SELLERS         seller_zip_code_prefix     int64
43                       SELLERS                    seller_city       str
44                       SELLERS                   seller_state       str
45  PRODUCT_CATEGORY_TRANSLATION          product_category_name       str
46  PRODUCT_CATEGORY_TRANSLATION  product_category_name_english       str
47                   GEOLOCATION    geolocation_zip_code_prefix     int64
48                   GEOLOCATION                geolocation_lat   float64
49                   GEOLOCATION                geolocation_lng   float64
50                   GEOLOCATION               geolocation_city       str
51                   GEOLOCATION              geolocation_state       str

In [21]:
datatype_df[
    datatype_df["Data_Type"] == "object"
]

Empty DataFrame
Columns: [Table, Column, Data_Type]
Index: []

In [22]:
primary_keys = {
    "CUSTOMERS": ["customer_id"],
    "ORDERS": ["order_id"],
    "ORDER_ITEMS": ["order_item_id"],
    "ORDER_PAYMENTS": ["payment_sequential"],
    "ORDER_REVIEWS": ["review_id"],
    "PRODUCTS": ["product_id"],
    "SELLERS": ["seller_id"],
    "PRODUCT_CATEGORY_TRANSLATION": ["product_category_name"],
    "GEOLOCATION": ["geolocation_zip_code_prefix"]
}

In [23]:
pk_summary = []

for table_name, columns in primary_keys.items():

    df = tables[table_name]

    for column in columns:

        duplicate_count = df[column].duplicated().sum()
        null_count = df[column].isnull().sum()
        total_rows = len(df)

        pk_summary.append({
            "Table": table_name,
            "Primary_Key": column,
            "Total_Rows": total_rows,
            "Null_Count": null_count,
            "Duplicate_Count": duplicate_count,
            "Is_Unique": duplicate_count == 0,
            "Has_Null": null_count > 0
        })

pk_df = pd.DataFrame(pk_summary)

pk_df

,Table,Primary_Key,Total_Rows,Null_Count,Duplicate_Count,Is_Unique,Has_Null
0,CUSTOMERS,customer_id,99441,0,0,True,False
1,ORDERS,order_id,99441,0,0,True,False
2,ORDER_ITEMS,order_item_id,112650,0,112629,False,False
3,ORDER_PAYMENTS,payment_sequential,103886,0,103857,False,False
4,ORDER_REVIEWS,review_id,99224,0,814,False,False
5,PRODUCTS,product_id,32951,0,0,True,False
6,SELLERS,seller_id,3095,0,0,True,False
7,PRODUCT_CATEGORY_TRANSLATION,product_category_name,71,0,0,True,False
8,GEOLOCATION,geolocation_zip_code_prefix,1000163,0,981148,False,False

In [24]:
orders["order_status"].value_counts()

order_status
delivered      96478
shipped         1107
canceled         625
unavailable      609
invoiced         314
processing       301
created            5
approved           2
Name: count, dtype: int64

In [25]:
order_reviews["review_score"].value_counts().sort_index()

review_score
1    11424
2     3151
3     8179
4    19142
5    57328
Name: count, dtype: int64

In [26]:
order_reviews["review_score"].describe()

count    99224.000000
mean         4.086421
std          1.347579
min          1.000000
25%          4.000000
50%          5.000000
75%          5.000000
max          5.000000
Name: review_score, dtype: float64

In [27]:
order_reviews[
    ~order_reviews["review_score"].isin([1, 2, 3, 4, 5])
]

Empty DataFrame
Columns: [review_id, order_id, review_score, review_comment_title, review_comment_message, review_creation_date, review_answer_timestamp]
Index: []

In [28]:
order_payments["payment_installments"].describe()

count    103886.000000
mean          2.853349
std           2.687051
min           0.000000
25%           1.000000
50%           1.000000
75%           4.000000
max          24.000000
Name: payment_installments, dtype: float64

In [29]:
order_payments[
    order_payments["payment_installments"] <= 0
]

,order_id,payment_sequential,payment_type,payment_installments,payment_value
46982,744bade1fcf9ff3f31d860ace076d422,2,credit_card,0,58.69
79014,1a57108394169c0b47d8f876acc9ba2d,2,credit_card,0,129.94

In [30]:
order_items["price"].describe()

count    112650.000000
mean        120.653739
std         183.633928
min           0.850000
25%          39.900000
50%          74.990000
75%         134.900000
max        6735.000000
Name: price, dtype: float64

In [31]:
order_items[
    order_items["freight_value"] < 0
]

Empty DataFrame
Columns: [order_id, order_item_id, product_id, seller_id, shipping_limit_date, price, freight_value]
Index: []

In [32]:
order_items[
    order_items["price"] < 0
]

Empty DataFrame
Columns: [order_id, order_item_id, product_id, seller_id, shipping_limit_date, price, freight_value]
Index: []

In [33]:
order_items[
    order_items["freight_value"] < 0
]

Empty DataFrame
Columns: [order_id, order_item_id, product_id, seller_id, shipping_limit_date, price, freight_value]
Index: []

In [34]:
order_items[
    order_items["freight_value"] < 0
]

Empty DataFrame
Columns: [order_id, order_item_id, product_id, seller_id, shipping_limit_date, price, freight_value]
Index: []

In [35]:
def find_outliers(df, column):

    Q1 = df[column].quantile(0.25)
    Q3 = df[column].quantile(0.75)

    IQR = Q3 - Q1

    lower_limit = Q1 - 1.5 * IQR
    upper_limit = Q3 + 1.5 * IQR

    outliers = df[
        (df[column] < lower_limit) |
        (df[column] > upper_limit)
    ]

    return outliers

In [36]:
price_outliers = find_outliers(
    order_items,
    "price"
)

print("Price outliers:", len(price_outliers))

Price outliers: 8427

In [37]:
freight_outliers = find_outliers(
    order_items,
    "freight_value"
)

print("Freight value outliers:", len(freight_outliers))

Freight value outliers: 12134

In [39]:
quality_report = {
    "Missing Values": missing_df,
    "Duplicates": duplicate_df,
    "Primary Key Check": pk_df,
    "Data Types": datatype_df
}
quality_report["Missing Values"]
quality_report["Primary Key Check"]
quality_report["Primary Key Check"]

,Table,Primary_Key,Total_Rows,Null_Count,Duplicate_Count,Is_Unique,Has_Null
0,CUSTOMERS,customer_id,99441,0,0,True,False
1,ORDERS,order_id,99441,0,0,True,False
2,ORDER_ITEMS,order_item_id,112650,0,112629,False,False
3,ORDER_PAYMENTS,payment_sequential,103886,0,103857,False,False
4,ORDER_REVIEWS,review_id,99224,0,814,False,False
5,PRODUCTS,product_id,32951,0,0,True,False
6,SELLERS,seller_id,3095,0,0,True,False
7,PRODUCT_CATEGORY_TRANSLATION,product_category_name,71,0,0,True,False
8,GEOLOCATION,geolocation_zip_code_prefix,1000163,0,981148,False,False